### ISSUE TITLE
ModuleNotFoundError: No module named 'juno'

### ISSUE THREAD

**Issue by marcorilli** [DeMarcoLab/juno#59]
On starting the tutorial, after following installation and running:

(juno)>juno_ui

I get: 
Traceback (most recent call last):
  File "C:\Users\XX\Anaconda3\envs\juno\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\XX\Anaconda3\envs\juno\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\XX\Anaconda3\envs\juno\Scripts\juno_ui.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'juno'

I'd like to request assistance with this.. 
[I have modest familiarity with anaconda pip, python, jupyter] I am running on windows 10.

**Comment by Bhavesh012** [comment]
I am having the same issue.
```
(juno) bhavesh@Bhaveshs-MBP KOOL % juno_ui
zsh: command not found: juno_ui
```
Do we have to put this path or create some kind of alias?

I am running this on M1 Pro with Python 3.8 and napari with PySide2.
